version: '3.8'

services:
  patient-service-db:
    image: postgres:16
    container_name: patient-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest  #  A Kafka image supporting KRaft mode
    container_name: kafka
    environment:
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal

  patient-service:
    build:
      context: patient-service
    container_name: patient-service
    depends_on:
      - patient-service-db
      - billing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    ports:
      - "4000:4000"
    networks:
      - internal

  billing-service:
    build:
      context: billing-service
    container_name: billing-service
    environment:
      SPRING_APPLICATION_NAME: billing-service
      SERVER_PORT: 4001
      GRPC_SERVER_PORT: 9001
      SPRING_PROFILES_ACTIVE: docker
      LOGGING_LEVEL_ROOT: INFO
    ports:
      - "4001:4001"  # HTTP port
      - "9001:9001"  # gRPC port
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:4002/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
    networks:
      - internal

networks:
  internal:
    driver: bridge