plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.pm'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

bootJar {
    archiveFileName = 'patient-service.jar'
    layered {
        enabled = true
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://maven.pkg.github.com/sagar-karatagi/grpc-proto")
        credentials {
            // ENV VARS DON'T WORK SOMETIME
            username = project.findProperty("gpr.user") ?: System.getenv("GPR_USER") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key")  ?: System.getenv("GPR_KEY")  ?: System.getenv("GITHUB_TOKEN")

        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Custom artifact containing generated protos
    implementation "com.pm:pm-protos:1.0.0"

    // gRPC client dependencies
    implementation 'io.grpc:grpc-netty-shaded:1.69.0'
    implementation 'io.grpc:grpc-protobuf:1.69.0'
    implementation 'io.grpc:grpc-stub:1.69.0'
    implementation 'com.google.protobuf:protobuf-java:4.29.1'
    
    //----------Kafka-----------//
    // Use the Spring Boot starter for Kafka for simplified dependency management
//    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.springframework.kafka:spring-kafka:3.3.0'

    // If you need Kafka Streams, add this dependency. Spring Boot will manage the version.
    // implementation 'org.apache.kafka:kafka-streams'
    //-------------------------//

    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}